### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by andrerom**
Replaces #7

TODO:
- [x] cleanup/simplify
- [x] updates to align with 16.02/16.04 _(env variables use)_
- [x] split out dev image
- [x] Blackfire
- [x] test on ezplatform travis-docker branch https://github.com/ezsystems/ezplatform/pull/97

**Size**: 249 MB => prod: 213 MB, dev: 247 MB  _( see [v0.4 images](https://hub.docker.com/r/ezsystems/php/tags/) )_

### CODE REVIEW

**Comment by vidarl** [comment]
I haven’t tested this, but looks good to me
+1

**Comment by andrerom** [comment]
@vidarl Ok, back to passing now after the cleanup changes, however one issue remains:
- permissions does not work for two users, can't execute using ez user w/o messing up for www-data and vica versa. Only thing that fixes this is to apply ACL on run.sh here, so pleas see if I have overlooked something on the permissions here (and in linked ezplatform repo PR), otherwise we'll need to re-add acl I think, and then question is where we can do it, in volume container itself? Or will it not stick there because of aufs filesystem _(even if folder is marked as volume)_?

Also note that `prepare_distribution_volume.sh` _(which I assume is either misplaced, and/or missnamed)_ has not been updated for the changes here yet.

**Comment by andrerom** [comment]
@vidarl Merged, however I thought we would have the acl stuff in run.sh.

When/where is set_permissions.sh used again?

**Comment by vidarl** [comment]
We can put set_permissions.sh in run.sh, yes

But strictly speaking, set_permissions.sh do not have to be executed every time the container starts. It only needs to be ran once.

But the most convenient thing would be to just exec it from run.sh

**Comment by andrerom** [comment]
@vidarl Added in https://github.com/ezsystems/docker-php/blob/updates/php/scripts/run.sh#L64

Q: `/scripts/set_permissions.sh --dev` will set ez user as owner of whole install, however isn't it safer to use acl to give ez these rights? as in how will that owner change affect local install if you mount is as volume when doing development?

**Comment by vidarl** [comment]
Not sure if matters in regards to "safety" ..?
Currently, set_permissions uses ACLs only on the directories which needs to be writeable to www-user  ( var, cache log dirs ). Other files/directories are managed by ownership.
We could change this to use ACLs too, but I don't yet imagine a use-case where it matters much.
Maybe we need to make the UID/GID 10000 configureable somehow, but whetever we should implement it using chown or ACLs is not clear for me at the moment. I think we would then need some usecases

**Comment by andrerom** [comment]
> it using chown or ACLs is not clear for me at the moment. I think we would then need some usecases

ok

**Pull request merged**
