### PR TITLE
Adding BCMath for Allure reports purpose

### PR DESCRIPTION
**Pull request by m-tyrala**
https://jira.ez.no/browse/EZP-30376

Behat Allure extension requires BCMath to work ( https://travis-ci.com/ezsystems/ezplatform-page-builder/jobs/226247467#L1657 )

### CODE REVIEW

**Comment by m-tyrala** [comment]
If i see correctly, there's no issues besides this one

>   ERR  WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
>   ERR  
>   ERR  You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:
>   ERR  
>   ERR    npm install --save core-js@2    npm install --save core-js@3
>   ERR    yarn add core-js@2              yarn add core-js@3
>   ERR  

which comes from master branch.

**Review by micszo — APPROVED** [review]

**Comment by andrerom** [comment]
Nope ;)

The reason it fails is the chaged done by @mnocon in https://github.com/ezsystems/ezplatform/commit/8185ef7339b10e74d9418faa75b4ff286becdeee#diff-353744a4ec6dd6515249072fc862bb04

ref: `.FileNotFoundError: [Errno 2] No such file or directory: './doc/docker/install.yml'`

**Comment by m-tyrala** [comment]
Yes, I've done a confusing simplification here, I meant that the error is not related to my change.

**Comment by andrerom** [comment]
Sure, but it needs to be fixed before we can merge this _(different PR or not)_. Otherwise you won't get any PHP7.1+ builds of this anyway as docker hub deployment is automatically done on green builds  ;)

**Review by mnocon — COMMENTED** [review]
About Travis: I will prepare a separate PR that should fix the build (based on https://github.com/ezsystems/ci/pull/26)

Two things about this PR:
1) Given that this is a dependency of a dev package (Behat extension), maybe it should be installed only for the dev flavour? https://github.com/ezsystems/docker-php/blob/master/php/Dockerfile-dev
2) If we're doing this for eZ Platform 2.5 then it needs a update doc entry for the requirements - all developers will have to update their envs

**Comment by andrerom** [comment]
> 1. Given that this is a dependency of a dev package (Behat extension), maybe it should be installed only for the dev flavour?

Do we always run behat tests using dev image? if so then yes, but afaik we used to at least also run some tests on prod images.

> If we're doing this for eZ Platform 2.5 then it needs 

😐 Hmm, this is not really a bundle partners usually use, but as we ship it with the product you are (kind of) right 

But this is only for our own reporting needs right? So it's a bit pity we end up having to bump requirements on stable version for this.. _(no value, for additional effort)_

**Comment by mnocon** [comment]
> Do we always run behat tests using dev image? if so then yes, but afaik we used to at least also run some tests on prod images.

Good point, I wouldn't bet my arm that we only use `dev` - can stay that way then

**Comment by m-tyrala** [comment]
I've investigate a little, if we can somehow workaround this relation, but it seems that it's required by more than one bundle and it is used in multiple places for handling UUID.

Maybe it'll be better for us and our customers to limit this change to dev env, check if we run behat on the other ones (if yes, would it even be proper and desirable?), and handle it in that cases?

**Comment by andrerom** [comment]
No strong opinions on my side, even if we add it as is, it does not necessarily mean it's a requirement, it can also be a recommendation.

**Review by andrerom — APPROVED** [review]

**Pull request merged**
