### PR TITLE
Add PHP_FPM_INI_ENV_ support

### PR DESCRIPTION
**Pull request by wizhippo**

### CODE REVIEW

**Review by andrerom — APPROVED** [review]
Looks ok to me, but I'll let @mnocon have the final say here :)

**Review by mnocon — CHANGES_REQUESTED** [review]
Thanks for your contribution, this looks useful!
One thing I've noticed when testing it - the default config from php-fpm looks like this:
```
; Include one or more files. If glob(3) exists, it is used to include a bunch of
; files from a glob(3) pattern. This directive can be used everywhere in the
; file.
; Relative path can also be used. They will be prefixed by:
;  - the global prefix if it's been set (-p argument)
;  - /usr/local otherwise
include=etc/php-fpm.d/*.conf
```

So the settings don't work when the file is called `/usr/local/etc/php-fpm.d/zzz_custom_settings.ini` (they are not imported).

I've tested that once the file is renamed to `zzz_custom_settings.conf` everything works as expected.

**Review by mnocon — APPROVED** [review]
Looks good now, thanks!

**Comment by andrerom** [comment]
@mnocon I guess you can merge this into v1, merge v1 into master, then after that
- adapt v1 to no longer tag "global" tags, merge and merge up
- then merge your PR

Or?

**Comment by mnocon** [comment]
@andrerom yep, that sounds right, the only thing is that I need https://github.com/ezsystems/ezplatform/pull/588 to be merged before #52 (otherwise the build won't pass)

I will start working on merging this and adapting v1 branch to prepare for #52 merge

**Comment by mnocon** [comment]
Thank you @wizhippo!

**Pull request merged**
